### ISSUE TITLE
No tests run for project which aggregates others

### ISSUE THREAD

**Issue by leszekgruchala** [scalacenter/bloop#101]
Bloop version: `66018e0a`

I have multi module sbt project.
- core
- web (which depends on core)
- root (which aggregates core and web).

Running tests on root does nothing
```
bloop -- test -p root
bloop -- test -p root-test
```
No output at all.

I have to run tests on project which contains them.

**Comment by jvican** [comment]
Can you not do `--aggregate`?

**Comment by leszekgruchala** [comment]
`bloop -- test -p root-test --aggregate` helped 👍

**Comment by leszekgruchala** [comment]
Can you derive this information from sbt configuratation?

**Comment by jvican** [comment]
We do have all that information from sbt, I guess that what you want is the `--aggregate` is enabled directly for "root" sbt projects, right? If this is what you wanted it wasn't clear :smile:.
  
A better and cleaner option than that one would be to make `--aggregate` the default, since it's the most common anyway. We would add `--isolated` or `--single` to signal that only the single project should be tested.
