### ISSUE TITLE
Add sbt-bloop offloading compilation instructions 

### ISSUE THREAD

**Issue by Baccata** [scalacenter/bloop#1116]
I'm trying out the offloading feature that was merged to master ~1 month ago (despite it not being documented)  

I'm encountering a number of weird bugs in the context of multi-module builds. There are numerous, and I'm having a hard time producing minimal-reproducible examples (it's a work project, can't just upload it). I need to debug the sbt-bloop plugin against it to be able to formulate issues in a clear manner (or even PR it myself if I find fixes) 

I'm not quite sure what's the best way to proceed. Could the dev workflow that was used during the development of the offloading feature be documented ? (or even loosely described in this ticket?) 

@jvican, asking here as I've not seen you online on gitter/discord recently.

**Comment by jvican** [comment]
Hi @Baccata, one of the reasons why it hasn't been publicized/documented yet it's because I'm aware of many of these small issues that add up and give the impression the feature doesn't work. I intend to fix these and when I do I'll make sure I modify the website to correctly reflect how people should interact with compile offloading. Thanks for creating this ticket to gather some clarity around the current situation.

**Comment by jvican** [comment]
> I'm encountering a number of weird bugs in the context of multi-module builds. There are numerous, and I'm having a hard time producing minimal-reproducible examples

@Baccata Could you describe them whenever you have some time? I'd like to fix this asap and I know of several issues regarding offloading compilation, but maybe the ones you ran into are different. Thanks for opening this ticket and early tester btw :smile:

**Comment by Baccata** [comment]
If I recall correctly, the most pernicious one was preventing SBT to restart, due to compile errors in code present in `$wd/project` (this was happening in a project that has a number of inlined sbt plugins). Calling sbt without the offloading flag would just work.
