### ISSUE TITLE
Add support for sources globs

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/bloop#1164]
Currently, the Bloop JSON configuration has as "sources" field which contains a list of files and directories.
```json
{
  "sources": ["/path/to/A.scala", "/path/to/src/scala"]
}
```

Some build tools like Pants and Bazel support globs like this
```
scala_library(
  name = "foo",
  sources = rglobs("Foo*.scala", excludes = ["*Test.scala"])
)
```

The sources for the "foo" target include

* all files that match the glob `Foo*.scala`
* excluding files that end with `*Test.scala`

It would be nice if the Bloop JSON config supported this somehow, for example with a new `sourcesGlobs` field
```json
{
  "sources": [ "... same as before ..." ],
  "sourcesGlobs": {
    "includes": ["/path/to/**/Foo*.scala"],
    "excludes": ["/path/to/**/*Test.scala"]
  }
}
```

**Comment by jvican** [comment]
Thanks for taking the time to document source glob support @olafurpg
  
Would it make sense to reuse the existing `sources` field and add the `include-glob:` or `exclude-glob:` prefixes for every item of the sources array, instead of having an independent field for it?
  
Also, do source globs apply to directories or only files?

**Comment by olafurpg** [comment]
@jvican I've thought about that and I think that design might be problematic for the current bloop-config API that uses `List[Path]`. We would need to convert that into `List[String]` if we go ahead with that design (which might be an OK tradeoff).
