### ISSUE TITLE
Typo in gradle configuration docs

### ISSUE THREAD

**Issue by aleksander-newstore** [scalacenter/bloop#1180]
The guide mentions Gradle version 4.8 which came out in June'18. The instructions mentioned no longer work, eg `apply plugin bloop` seems to be no longer valid syntax. As a person with not much Gradle experience it's difficult for me to work out the details of what exactly needs to be updated to make it work ...

**Comment by aleksander-newstore** [comment]
it's possible that the only thing thats needed is to add `:` after `apply plugin:`

**Comment by aleksander-newstore** [comment]
another issue:
if as in the guide I add 
```
allprojects {
  apply plugin: 'bloop'
}
```
metals log contains a line:
`Cannot add extension with name 'bloop', as there is an extension already registered with that name.`
and the initialisation fails

**Comment by Arthurm1** [comment]
If you're only using **Import Build** from Metals then there is no need to manually add the Bloop plugin to your project.

If you're adding the Bloop plugin because you want to manually run **gradlew bloopInstall** then you can write...
```
if (!plugins.hasPlugin('bloop')) {
  apply plugin: 'bloop'
}
```
... which shouldn't conflict with Metals

I think you're correct: `apply plugin 'bloop'` should probably be `apply plugin: 'bloop'` in the docs or better - the above snippet.  PRs welcome :-)

FYI - the mention of Gradle version 4.8 in the docs is just to show why using Bloop for Scala compilation might be better than using Gradle.  The Bloop plugin supports Gradle versions 4.3 -> 6.0.

**Comment by jvican** [comment]
@aleksander-newstore Thanks for bringing this up, this might be a small issue in the docs. I can say I'm using bloop with Gradle successfully at work where we use a heavily customized Gradle called Nebula. So if it works there it must work in your project. Let me know if the fixes that @Arthurm1 mentions have fixed your issue.
  
I'm going to start investing some resources in the project to make Gradle a first-class citizen in our docs and support line. This will most likely require me to work on a few issues and docs, but I might need some help. Would you be interested in getting involved in something like this?
