### ISSUE TITLE
Running a project while another is running may yield `java.lang.NoClassDefFoundError`

### ISSUE THREAD

**Issue by kubukoz** [scalacenter/bloop#1189]
I'm using Metals in a project and running one of the projects in background (`bloop run proj1`).

In the meantime, I edited some files (in fact, they are shared by both projects), and ran another project (`bloop run proj2`) in the same source root.

I got a NoClassDefFoundError in `proj2`, mentioning one of the classes in one of the modified files.

I know it's a tricky problem because I shouldn't expect two versions of the same class to exist in runtime, but maybe there's a more graceful solution? E.g. killing the running application, or failing compilation if the files involved in it are in use by another project?

Bloop stats:

```
bloop v1.4.0-RC1-69-693de22a

Using Scala v2.12.8 and Zinc v1.3.0-M4+32-b1accb96
Running on Java JDK v11.0.6 (/Users/kubukoz/.sdkman/candidates/java/19.3.1.r11-grl)
```

**Comment by jvican** [comment]
@kubukoz Thanks for reporting! I'm aware of this issue and want to fix it soon.

**Comment by jvican** [comment]
> I know it's a tricky problem because I shouldn't expect two versions of the same class to exist in runtime, but maybe there's a more graceful solution? E.g. killing the running application, or failing compilation if the files involved in it are in use by another project?
  
Bloop is actually built, from first principles, to address this scenario and let you have as many concurrent clients running and using the build resources. Bloop isolates the different clients you have running (Metals, CLI, other tools) so that you don't run into these issues.
  
You're running into this issue (and I've run into this too) because of a tricky bug I'm chasing down and hope to have fixed soon. Thanks for reporting, again, @kubukoz

**Comment by jvican** [comment]
The next release will have this fix /cc @nafg since you reported essentially a dupe of this ticket. I recommend you both upgrade to the latest bloop version. Thanks for your detective work.
