### ISSUE TITLE
Expected non-zero exit code when CLI compile fails

### ISSUE THREAD

**Issue by PAStheLoD** [scalacenter/bloop#1192]
Hello,

We tried to integrate bloop into our CI flow, and at first everything seemed magical, but then on one run it finished pretty fast, the run was marked successful, yet the log was full of compile errors.

We're launching the client like this: `python3 /var/lib/gitlab-runner/.bloop/bloop test ourFancyProject` and then a simple `exit $?` is used.

Here's the log from the CI run:

```
 + python3 /var/lib/gitlab-runner/.bloop/bloop test ourFancyProject
Compiling ourFancyProject (668 Scala sources)

...

[E] app/core/actors/someActor.scala: L94 [E25], L95 [E26], L96 [E27], L97 [E28], L98 [E29], L99 [E30], L100 [E31], L101 [E32], L102 [E33], L103 [E34], L104 [E35], L105 [E36], L106 [E37], L107 [E38], L131 [E11], L132 [E12], L133 [E13], L134 [E14], L135 [E15], L136 [E16], L137 [E17], L138 [E18], L139 [E19], L140 [E20], L141 [E21], L142 [E22], L143 [E23], L144 [E24], L670 [E39], L817 [E40], L820 [E41], L820 [E42], L822 [E43], L822 [E44], L823 [E45], L826 [E46], L826 [E47], L828 [E48], L834 [E49], L839 [E50], L839 [E51], L840 [E52], L840 [E53]
Compiled ourFancyProject (219316ms)
[E] Failed to compile 'ourFancyProject,'ourFancyProject-test'
+ exit 0
```

Interestingly the same commit compiles using sbt.

It's pretty likely that we are somehow "holding it wrong". Eg. what happens if new files are added to the repository, should we call bloopInstall again? However, this exit status bug seems unrelated to that, hence this report.

**Comment by jvican** [comment]
@PAStheLoD Thanks for reporting!

> We're launching the client like this: python3 /var/lib/gitlab-runner/.bloop/bloop test ourFancyProject and then a simple exit $? is used.
  
I recommend using `bloopgun`, our Scala-based and native CLI. You can use `coursier` to invoke it.
  
> It's pretty likely that we are somehow "holding it wrong". Eg. what happens if new files are added to the repository, should we call bloopInstall again? 
  
It is not recommended to use bloop in the CI. Bloop uses incremental compilation, so your CI might fail because of an incremental compiler error. The well-established standard is to have non-incremental compilation.
  
However, you can use bloop to run a resident bloop server in your Jenkins CI (only possible in Jenkins or other machines that are long-running). In the future, it'll be possible to just have sbt use Bloop compilation under the hood for any compilation happening in your CI, bringing you faster compiles automatically, but we're not there yet (working towards it, though).

> However, this exit status bug seems unrelated to that, hence this report.
  
Yes, this might be an error. Following the logic inside bloop to catch where this bug is happening is relatively easy, you can start in `Cli.scala` and `Interpreter.scala` if you want to help out fix it, which is very welcome.

**Comment by tgodzik** [comment]
We no longer allow launching bloop this way.
