### ISSUE TITLE
Add support for Android projects in Gradle

### ISSUE THREAD

**Issue by Elephant454** [scalacenter/bloop#1201]
I set up the Gradle plugin and did a `./gradlew bloopInstall -Si` and was told

`Ignoring 'bloopInstall' on non-Scala and non-Java project 'RadiusMessage'`

I looked at the build.gradle for my app, and it is indeed an Android project as opposed to a Java project. How difficult would it be to add minimal Android support in order to allow compilation of Java code?

**Comment by jvican** [comment]
> I looked at the build.gradle for my app, and it is indeed an Android project as opposed to a Java project. How difficult would it be to add minimal Android support in order to allow compilation of Java code?
  
I don't think it should be difficult. f we can indeed export an Android project safely it'd be enough to whitelist it in the sources of the gradle plugin. Mind looking into it? @Elephant454

**Comment by jvican** [comment]
I've never worked on Android projects in Gradle, but which JDK does the Android project require for compilation? Can we assume you won't run the android project with bloop and that you'll keep using Gradle?

**Comment by Elephant454** [comment]
@jvican I would love to look into it. 🙂

I think the project can use whichever JDK version, as the Gradle config doesn't seem to specify one. Android Studio is currently set to use its own internal JDK version, which is OpenJDK 1.8.

Yes, I would like to continue using Gradle. My plan is to be switching between using Android Studio and Emacs (with Metals).

**Comment by jvican** [comment]
> Yes, I would like to continue using Gradle. My plan is to be switching between using Android Studio and Emacs (with Metals).
  
Cool, so long as you don't run your android project with bloop that should be fine. I would expect that running your android project with the JVM bloop uses would make it crash because IIRC Android projects don't work well with JDK >= 8.
  
I encourage you to have a look at the gradle plugin sources (the entrypoint is `bloop.integrations.gradle.BloopPlugin`) and change the code to make it work with android projects. The best way to go around this is to add a test that includes some minimal android configuration, run the test and see how it behaves. Let me know if I can help out with something and I'll try to chime in as my time allows. Thanks

**Comment by Elephant454** [comment]
I've never worked on a codebase this large before, and I've never worked in Scala either, but this has certainly piqued my interest. I'll let you know what I find. :slightly_smiling_face:

**Comment by jvican** [comment]
Let me know whenever you pick this up @Elephant454

**Comment by Arthurm1** [comment]
This can probably be closed because of #1464

**Comment by tgodzik** [comment]
Thanks!
