### ISSUE TITLE
Missing index.html after ScalaTest execution

### ISSUE THREAD

**Issue by eanderson13** [scalacenter/bloop#1274]
Bloop doesn't generate the ScalaTest index.html test summary file when using the `-h` option

Steps to reproduce:

```
git clone git@github.com:eanderson13/bloop-scalatest.git
cd bloop-scalatest
sbt assembly bloopInstall sbt/test
scala -cp target/scala-2.13/bloop-scalatest-assembly-0.1.0-SNAPSHOT.jar org.scalatest.tools.Runner -R target/scala-2.13/test-classes -h target/html
bloop test bloop
[ -f sbt/target/html/index.html ] && echo "sbt generates index.html" || echo "sbt doesn't generate index.html"
[ -f bloop/target/html/index.html ] && echo "bloop generates index.html" || echo "bloop doesn't generate index.html"
```

**Comment by jvican** [comment]
Thanks for reporting @eanderson13. I don't know why this is happening. It might be because sbt is doing the `index.html` generation itself or calling some scalatest logic to do it? Bloop doesn't do that. We do generate an `ExampleSpec.html`.

![Screen Shot 2020-05-12 at 10 20 21](https://user-images.githubusercontent.com/2462974/81659649-32d42780-943a-11ea-80ef-96a2fe353cef.png)

I can't dig into this. I'd be happy if someone can look into this so that we can evaluate to which extent bloop can support the generation of the `index.html` file.

**Comment by eanderson13** [comment]
I explored some of the other options ScalaTest supplies for running tests, and found that both their native runner and the IntelliJ plugin both generate index.html.
I updated the test project to demonstrate the native runner and the screenshot below shows the IntelliJ configuration used.
<img width="723" alt="intellij-scalatest" src="https://user-images.githubusercontent.com/6733038/81759237-04c20800-9479-11ea-9e13-953d9bc61738.png">

**Comment by eanderson13** [comment]
I happened across this note in the ScalaTest docs, which I'm guessing is what's missing: https://github.com/scalatest/scalatest/blob/master/scalatest/src/main/scala/org/scalatest/tools/Framework.scala#L116-L119
