### ISSUE TITLE
How to start bloop server in background and know it has been started?

### ISSUE THREAD

**Issue by davidmlw** [scalacenter/bloop#1292]
In a script, one may need to start bloop server, bloop work, work done, bloop stop server, leave. like:

```
bloop server # line 1
bloop compile projectA # line 2
bloop run -p projectA main args
bloop ng-stop
```
While this is not working, because line 1 will not quit. But if use `bloop server &` then it has race problem with line 2, because line 1 takes some time to start the server.

Is there some option or shell tips to start bloop server, make sure it has been started, and submit jobs to the server?

**Comment by Duhemm** [comment]
You don't need to run `bloop server` beforehand. If a server is already available on Bloop's default port (`8212`), then this instance will be used, otherwise a new instance will be started.

If you need to be sure to use a new Bloop server for you run, then you can invoke Bloop with `--nailgun-port <my-port>`.

To kill the server, use `bloop exit`.

This should give you the behavior you're looking for:
```
bloop --nailgun-port 8213 compile projectA
bloop --nailgun-port 8213 run -p projectA main args
bloop --nailgun-port 8213 exit
```

In the future, please prefer gitter (https://gitter.im/scalacenter/bloop) for support questions.

**Comment by davidmlw** [comment]
Nice!
