### ISSUE TITLE
Releases are failing in CI

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/bloop#1320]
From https://github.com/scalacenter/bloop/runs/787304809?check_suite_focus=true#step:7:988
```
[error] sbt.internal.util.Init$RuntimeUndefined: References to undefined settings at runtime.
[error] setting(ScopedKey(Scope(Select(ProjectRef(file:/home/runner/work/bloop/bloop/,bloop)), Zero, Zero, Zero),releaseSonatypeBundle)) at LinePosition(/home/runner/work/bloop/bloop/build.sbt,904) referenced from ScopedKey(Scope(Select(ProjectRef(file:/home/runner/work/bloop/bloop/,bloop)), Zero, Zero, Zero),sonatypeBundleRelease)
[error] 	at sbt.internal.util.Init.sbt$internal$util$Init$$handleUndefined(Settings.scala:693)
[error] 	at sbt.internal.util.Init$$anon$9.apply(Settings.scala:697)
```

@jvican Any idea what might be causing this issue?

**Comment by jvican** [comment]
No idea, I was trying to fix that last night. Just sbt not finding the scope when it should. I wonder if we should rerun that as a command instead of a task.

In the meanwhile it should be possible to get the offending task outside of the task dyn and force its evaluation. I can’t do this now but if someone does a PR we can merge and go ahead with the release.

**Comment by Duhemm** [comment]
I just opened #1321 which tries to fix it. I don't understand why sbt-sonatype defines a TaskKey called `sonatypeReleaseBundle`, which is apparently left unbound. Hopefully this should be fixed by calling the command `sonatypeReleaseBundle` instead, which apparently is what was being done 5 weeks ago.
