### ISSUE TITLE
Zinc and Scala versions

### ISSUE THREAD

**Issue by IlyaHalsky** [scalacenter/bloop#1382]
Hi,

I've noticed when calling `bloop about` it prints `Using Scala v2.12.8 and Zinc v1.3.0-M4+45-d4354be3`, 
I get why Scala version could be outdated, but Zinc is now 1.4.0 (4 days ago) with previous minor version being v1.3.5 (Mar 30). 
Is it intentional?

**Comment by tgodzik** [comment]
Thanks for the question! Bloop is using a separate fork of zinc, I don't remember exactly why, but I think it was connected to some changes needed for Bloop itself, which weren't possible merge upstream.

We should probably update the fork though.

**Comment by Duhemm** [comment]
Thanks for reporting @IlyaHalsky. Bloop is using a fork of Zinc, which includes some features that weren't available in vanilla Zinc at the time (build pipelining, for instance).

I'd personally be in favor of migrating back to sbt/zinc since it now includes all of the features that our fork has, and I believe it has received a significant number of other improvements that haven't been ported to our fork.

**Comment by Duhemm** [comment]
Closing in favor of #1383
