### ISSUE TITLE
Unclear commands documentation for flags usage of bsp

### ISSUE THREAD

**Issue by ivanopagano** [scalacenter/bloop#312]
The `commands-reference.md` page documents confusing usage of some flags related to the `protocol` option when calling `bloop bsp`, i.e.

 * note under `--protocol` says " when using the `tcp` protocol, the `--socket` option must be set, too."
 * under `--socket` says "this option can only be set when the `--protocol` is set to `only`."
 * under `--pipename` says "this option can only be set when the `--protocol` is set to `only`."
 * The accepted values for protocol are `local` and `tcp`

Since `only` is not a valid `--protocol` value, it's that somehow pointing to the fact that the flag should be set or not set at all?

All in all it's not clear to me how those three flags should be mixed

**Comment by ivanopagano** [comment]
I would contribute myself to correct this section if only I had an idea of what actually is the correct usage.

Also I can't make the project locally update its deps, but that maybe related to my local .ivy cache

**Comment by jvican** [comment]
> Also I can't make the project locally update its deps, but that maybe related to my local .ivy cache
  
This is a problem with our current sbt build... Could you add coursier as a global plugin directory? That will solve it -- I'm adding this step to our docs.
  
I recently added docs on how to improve our documentation in https://scalacenter.github.io/bloop/docs/developer-documentation/. I'm fixing this issue now (thank you for reporting!) but next time something is not clear, feel free to open a PR right away :smile:

**Comment by ivanopagano** [comment]
Thanks @jvican , do you guys plan to fix the coursier issue without forcing users to set it up globally?

I used to have it like so, but in time I had to work on client projects that wouldn't always work correctly, based on projects and deps versions, so I'm not very fond of such solution...

**Comment by jvican** [comment]
> Thanks @jvican , do you guys plan to fix the coursier issue without forcing users to set it up globally?
  
Yeah, that's our plan in the long term, but the real fix to this issue has to happen in sbt/sbt which has issues with build dependencies. The main problem is that our benchmarking facilities depend on some stuff from our core project, and making them independent (and hence solving this issue) is not as easy as it sounds, and it definitely requires some time and dedication.
  
This is not the priority for now, we want to focus on the UX of bloop as a user (to make it successful) rather than as a contributor for now. But we do welcome PRs and would love to see some from you :wink:
