### ISSUE TITLE
Add autocompletions for flags of commands when no project is required

### ISSUE THREAD

**Issue by jvican** [scalacenter/bloop#356]
Support for completions has just been merged in #353. However, it's not yet complete. One thing that is missing is that we don't autocomplete flags of commands *when no project is required*.
  
That is, `bloop compile foo -<TAB>` autocompletes, but `bloop configure -` or `bloop compile -` doesn't.

**Comment by jvican** [comment]
@rberenguel As you're already familiar with how autocompletion works, fixing this ticket would be a good way to continue contributing to bloop :smile:.

**Comment by rberenguel** [comment]
:+1: got it

**Comment by rberenguel** [comment]
@jvican @Duhemm is [this](https://github.com/scalacenter/bloop/blob/master/etc/zsh/_bloop#L45) autogenerated? The problem is with `_arguments`, it's not smart enough for the usage we need here since it will always expects a project. If you ac `bloop configure` in a project folder, it will complete projects (but, configure expects no projects so makes little sense, adding a colon to the project option so it's optional makes run `bloop configure` outside of a project actually complete flags).

If this is not autogenerated, using directly the autocomplete API could be easier to follow. Or rewrite with a more complex version (ugh, shell scripts!) that can handle commands expecting projects and commands not expecting them.

This is an example from one of my autocomplete functions (I have a bunch for zsh... they come very handy, although officially the API is not stable yet IIRC). Being able to match the command should cover the usability issue we have here.

```bash
_fzf_complete_git() {
    ARGS="$@"
    local branches
    local issues
    if [[ $ARGS == 'git co -b'* ]]; then
        issues=$(cat ~/fromsource/jira-issues.list)
        _fzf_complete "--reverse --multi" "$@" < <(
            echo $issues
        )
    elif [[ $ARGS == 'git co'* ]]; then
        branches=$(git branch -vv --all | sed "s/remotes\/origin\///g" | sed "s/\*/ /g")
        _fzf_complete "--reverse --multi" "$@" < <(
            echo $branches
        )
    else
        eval "zle ${fzf_default_completion:-expand-or-complete}"
    fi
}
```

**Comment by jvican** [comment]
No, that's not autogenerated. My intuition is that what we need to do the following actions:
  
1. Make `_projects` optional for the commands that do not take project commands (we could add this query to the `autocomplete` command)
2. Detect automatically that anything starting with `-` is to be interpreted as a flag, and therefore no query to the projects is necessary. 
  
I've never tinkered with the autocompletion templates, so I don't know if this is possible. But it looks like it should. You probably have a better idea of how to achieve this than I do :wink:

**Comment by rberenguel** [comment]
Yep know how to do it in zsh @jvican and probably can handle it with bash too. I'll give it a think so it's easy to maintain and we don't need to rewrite it later on ;)

**Comment by rberenguel** [comment]
@jvican I gave it a first shot with https://github.com/scalacenter/bloop/pull/438 without needing to modify any of the Scala sources. Basically complicated the internal completion state machine with:
1. Expects a command
2. If in a project, and the command is a "project bound command", complete project. Otherwise, flags
3. Flags otherwise

This can be readily improved by adding a new `autocomplete` that can populate the list of project commands from the server. 

I haven't tried to get bash to work yet, zsh was harder than I expected. Tomorrow!
