### ISSUE TITLE
Handle cancellation of the REPL

### ISSUE THREAD

**Issue by jvican** [scalacenter/bloop#469]
For consistency with the rest of operations, the REPL should be gracefully cancelled whenever <kbd>Ctrl</kbd><kbd>C</kbd> is typed, otherwise the execution will never stop and could cause a potential deadlock. Currently, users can gracefully cancel it by typing `:q` as they usually do.

**Comment by jvican** [comment]
I meant the latter. The logic to handle cancellation is already present in ‘Cli.scala’ but it has no effect for console because we don’t do ‘doOnCancel’ upon the creation of the console task.

**Comment by tues** [comment]
This one was a bit tricky, because `AnalyzingCompiler.console` returns `Unit`, so obviously there's no way to close it externally. However, the REPL also exits when it encounters `EOF`. 

We can expect Nailgun to close `stdin` when a client disconnects, and indeed it seems to be the case: I attached a debugger and set a breakpoint in:
https://github.com/scalacenter/zinc/blob/0f4ad9d59f3f366d272f28aeec7949a5763018cb/internal/compiler-bridge/src/main/scala_2.11-12/xsbt/ConsoleInterface.scala#L72
The breakpoint was hit when typing `:q`, when pressing `ctrl+D` (manually sending `EOF`) and when pressing `ctrl+C` (sending `SIGINT`), so I think we can safely assume that cancellation is already handled.

I'm closing this issue for now, but if someone finds any evidence my assumptions aren't correct, feel free to reopen it.
