### ISSUE TITLE
Sbt plugin ignores Configuration.extends dependencies

### ISSUE THREAD

**Issue by tues** [scalacenter/bloop#515]
As mentioned in #512, this can be easily reproduced by adding:

```
val IntegrationTest = config("it") extend Test
```

before:
https://github.com/scalacenter/bloop/blob/d6bdcadf652380b609287fa33f802d30ae7448ac/integrations/sbt-bloop/src/sbt-test/sbt-bloop/custom-configurations/build.sbt#L3

This is caused by sbt's `Configuration.extendsConfigs` returning wrong data here:
https://github.com/scalacenter/bloop/blob/d6bdcadf652380b609287fa33f802d30ae7448ac/integrations/sbt-bloop/src/main/scala/bloop/integrations/sbt/SbtBloop.scala#L165

Expected behaviour:
`dependencies` should include `foo-test` instead of just `foo`.

**Comment by jvican** [comment]
The issue why this doesn't work is because configurations in sbt are by name, so any reference to `IntegrationTest` inside the sbt engine will fallback into the already existing `IntegrationTest` sbt configuration, which does not extend `Test`. The linked PR shows how changing the name from `"it"` to another string makes the sbt integration pick up the dependency on the test project.

**Comment by tues** [comment]
OK, so no chance to get this working without breaking existing sbt project? I think we should let people override such settings, especially since:
```
val IntegrationTest = config("it") extend Test
```
seems to be relatively common, e.g.: https://stackoverflow.com/a/20683597

**Comment by jvican** [comment]
I think there's nothing we can do, maybe you can have a closer look? The issue here seems to be sbt, that has by-name reference to configurations. Our use of the configuration APIs comes from:
https://github.com/scalacenter/bloop/blob/f7d1bbb7d28529d3479fb246338ffca766c461f2/integrations/sbt-bloop/src/main/scala/bloop/integrations/sbt/SbtBloop.scala#L181
  
All we're doing is iterating through the configurations set up in the project and checking if they are eligible or not. Maybe you can have a look and spot how we could detect this (kind-of-illegal) extension of `IntegrationTest`?

  
The part of sbt that defines the same configuration is here: https://github.com/sbt/librarymanagement/blob/6e4ad6ebd4042d3b9f1631b4a7a20d27aaa87db8/core/src/main/scala/sbt/librarymanagement/ConfigurationExtra.scala#L42
