### ISSUE TITLE
Simplify Maven plugin build process in the sbt build

### ISSUE THREAD

**Issue by lefou** [scalacenter/bloop#522]
I created a PR in scala-maven-plugin (https://github.com/davidB/scala-maven-plugin/pull/269) which makes the plugin configuration visible from the classfiles. Thus, the normal generation process for Maven Plugin Descriptors (`META-INF/maven/plugin.xml`) should work again.

Currently, the inherited configuration (based on javadoc-style annotation) is not visible and there is a lot of cruft to work around it in the sbt project setup.

After the PR got merged and an new version of the scala-maven-plugin is available, the sbt build should use the new opportunities and be cleaned up.

**Comment by lefou** [comment]
Btw, after that, it should also be possible to write the plugin in Scala instead of Java.

**Comment by lefou** [comment]
@jvican Although I understand, that you have to inherit from the scala-maven-plugin to get access to it's internal configuration (via some undocumented Maven-magic trickery), I do not understand why the `BloopMojo` class inself inherits from the scala-maven-plugin (or some of it's classes). IMHO, this inheritance makes any addition/change to the bloop plugin very hard.

**Comment by jvican** [comment]
If I understand your question correctly, the reason why we need to extend their classes is because they define maven settings that are set by maven via reflection. These fields are required in our end too and we want to re-use those without writing all the logic to process them, so that's why inheritance helps us here: we don't write the fields and the processing of them on our own before delegating them to the bloop converter.
  
Does that make sense?

**Comment by jvican** [comment]
Closing, I'm happy to reopen if someone clarifies what should be done here and leads the effort.
