### ISSUE TITLE
Add these user questions to the FAQ

### ISSUE THREAD

**Issue by gabro** [scalacenter/bloop#544]
Hi! 👋 
I've given an internal presentation about Bloop at my company and I've collected a few questions from the audience that I haven't found answered in the docs:

- can't the problem of losing a hot JVM be mitigated by the caching mechanism of JIT-ed code mentioned [here](https://docs.oracle.com/cd/B28359_01/java.111/b31225/chnine.htm#BABJFAIF)? I'll highlight here the relevant sentence:

> A JIT compiler for Oracle JVM enables much faster execution because, it manages the invalidation, recompilation, and storage of code without an external mechanism. Based on dynamically gathered profiling data, this compiler transparently selects Java methods to compile the native machine code and dynamically makes them available to running Java sessions. Additionally, **the compiler can take advantage of Oracle JVM's class resolution model to optionally persist compiled Java methods** across database calls, sessions, or instances. Such persistence avoids the overhead of unnecessary recompilations across sessions or instances, when it is known that semantically the Java code has not changed.

- bloop server maintains several compilers (aka JVMs) alive on my computer: what's the memory impact on my machine?

- can't I just run bloop from sbt directly? (this should be https://github.com/scalacenter/bloop/issues/315, but correct me if I'm wrong)

I hope this is useful and if the questions/answers are relevant maybe they can end up in the FAQ!

**Comment by jvican** [comment]
This is much appreciate Gabriele, thanks!

> can't the problem of losing a hot JVM be mitigated by the caching mechanism of JIT-ed code mentioned here?
  
The article linked just describes a custom Oracle-implemented integration between databases and the JIT, it doesn't go into details but has no relationship with mitigating the loss of JVM codes.
  
However, there's some experimentation about persisting JIT profiles to disk and reusing those to warm up the compiler directly instead of going through the normal compilation pipeline of Interpreter -> C1 -> C2. This isn't yet implemented, have a look at https://t.co/igJvbUMhSe.
  
There's another thing called Application Class-Data Sharing that intends to do something similar but it isn't as powerful. This one is available in JDK10. There have been experiments with this and it hasn't been proven to provide good performance results on cold compilation. http://openjdk.java.net/jeps/310
  
In essence, bloop always keeps your hot compiles by not doing anything fancy: just keeping the JIT profiles in memory along the computer session. However, note that even if JWarmup works (linked above), bloop will still provide value to users because it solves another main pain point in tooling: integrating with other tools via protocols.
   
> bloop server maintains several compilers (aka JVMs) alive on my computer: what's the memory impact on my machine?
  
There is only one JVM, the one running bloop. Every compiler is classloaded into an independent classloader that is optimized by the host JIT. The memory impact with bloop is much better than having two independent JVMs compiling different Scala versions.
  
> can't I just run bloop from sbt directly? (this should be #315, but correct me if I'm wrong)
  
That's correct. But note that it won't be as fast because sbt's task engine (given that it doesn't do caching) will recompute a lot of unnecessary stuff.
  
> I hope this is useful and if the questions/answers are relevant maybe they can end up in the FAQ!
  
I'll think about doing so soon.

**Comment by jvican** [comment]
Unfortunately I won't have time to add these questions to the FAQ soon, so I'm closing this ticket to avoid cluttering up the issue tracker... Help on this is very welcome.
