### ISSUE TITLE
Add a shutdown command in bloop

### ISSUE THREAD

**Issue by tindzk** [scalacenter/bloop#546]
I am running Bloop as follows in Drone CI:

```shell
blp-server &
bloop test project
```

However, after the execution of the test cases, the Bloop server is killed even before the analysis files has been written to disk. I could work around the problem by adding `sleep 5`.

A better solution would be one of the following:

1. `test` would only terminate once the analysis files were written
2. Introduce a blocking command `bloop shutdown`
3. Add a `--standalone` parameter to all commands that would run a Bloop server as part of the front-end (it would not have to listen to external connection)

**Comment by jvican** [comment]
I would rather lean towards a `dump` or `persist` command that would write all in-memory state to the disk. However, why do you need the analysis files to be written to disk in your CI? Are you processing the analysis files later on with another tool?

**Comment by tindzk** [comment]
@jvican Yes, or we could call it `sync` (in analogy to the `sync` command on Linux). The analysis files are shared across my CI builds. I thought they contain cache information such that future compilation passes can be performed incrementally.

**Comment by jvican** [comment]
Yes, the analysis files serve that purpose. However, I'm surprised you see they are not written quickly -- Bloop schedules a write to disk right after the client disconnects.
  
What is the current architecture in your CI? We should be able to handle this scenario when Bloop supports remote compilation. The idea is that you submit jobs and Bloop will compile, and you won't need to wait for analysis files to be written because subsequent compilation will immediately pick up the most recent analysis file in memory. This will also help fix some race conditions in compilation (the idea is that bloop server can handle remote *and* concurrent compilation gracefully to server different CI jobs at once).

**Comment by tindzk** [comment]
I created a minimal Docker instance for Bloop which is spawned by Drone CI. Right after the `test` command, the instance gets destroyed and I found that a few analysis files were missing.

Remote compilation is exactly what I am looking for, but it could be challenging to implement with Drone CI as the compilation jobs do not have direct access to the host system. As far as I know, they cannot even connect to any local servers, only via public IP, so the compilation server would need to implement authentication.

**Comment by jvican** [comment]
Whenever we do remote compilation, I propose we implement Bazel's remote compilation protocol https://github.com/bazelbuild/remote-apis. I'm closing this ticket since the addition of this command is a little bit ad-hoc IMO and the remote compilation protocol has concrete logic to handle this step.
