### ISSUE TITLE
Compile, link and test on several projects at once

### ISSUE THREAD

**Issue by tindzk** [scalacenter/bloop#575]
It should be possible to specify multiple projects when compiling, linking or testing:

```shell
bloop compile project1 project2
bloop link project1 project2
bloop test project1 project2
```

We need to make sure that this functionality also extends to the `--watch` parameter:

```shell
$ bloop compile --watch project1 project2
$ bloop link --watch project1 project2
$ bloop test --watch project1 project2
```

**Discussion:** https://gitter.im/scalacenter/bloop?at=5b2ceda1479ca2668975803b

**Comment by jvican** [comment]
The logic for this is already implemented since we support that in BSP. The only change required for this is in the CLI handling logic.

**Comment by jvican** [comment]
As said by @Duhemm in #578, we should probably allow `bloop test` to mean test all the projects in the build graph.

**Comment by BardurArantsson** [comment]
Hi, so I started to have a look at this...

I'm totally new to the code base, but I'm assuming it's reasonable to start from `Commands.scala` and to go "inwards"?

Two immediate questions:

- CompilingCommand demands a "project: String". This could probably easily be changed to List[String] and then doing the follow-up changes. However, the field gets used in e.g. "run" and "console" which perhaps doesn't make much sense. (I guess it would be possible to just do them sequentially? Or maybe special-case the command handling for them to just accept a list and then bail out if multiple projects are specified on the command line?)

- Wrt. the mechanism for actually running the "compile" (or whatever): Is the idea to just iterate sequentially through the projects in e.g. Interpreter#test() and get through all the projects that way? Would there be a risk of the ordering being wrong? I'm also assuming that this might lead to some duplicate work... or is the rest of the machinery clever enough that this won't be problem?

**Comment by jvican** [comment]
Hey @BardurArantsson, this is actually quite good timing to tackle this one. Yesterday I added the most critical blocker for this feature in https://github.com/scalacenter/bloop/commit/9cda6c7689e4a34d557f0eecd701fb8f9b12f40e, an aggregate node in our DAG abstraction (cherry-pick it in your branch before you start working on the ticket).
  
More to the point, let's answer your questions:

> CompilingCommand demands a "project: String". This could probably easily be changed to List[String] and then doing the follow-up changes. However, the field gets used in e.g. "run" and "console" which perhaps doesn't make much sense. (I guess it would be possible to just do them sequentially? Or maybe special-case the command handling for them to just accept a list and then bail out if multiple projects are specified on the command line?)
  
My preferred approach to this problem would be to change the interfaces in such a way that we minimize changes in the call-site. The current definition of `project` in `CompilingCommand` is required for pretty much all the logic of `Cli`.
  
So I would go for changing its type to `List[String]` and then add companion methods in the most used commands `Compile`, `Test`, `Run`, `Link` that allow the construction of a command given only a project name. Afterward, I would change the logic in `Cli`, `Interpreter` and maybe `Tasks` so that the commands that cannot take different projects (like you rightly intuited all the projects that are not `compile` and `test`) handle the case and print an error and exit.
  
> Wrt. the mechanism for actually running the "compile" (or whatever): Is the idea to just iterate sequentially through the projects in e.g. Interpreter#test() and get through all the projects that way? Would there be a risk of the ordering being wrong? I'm also assuming that this might lead to some duplicate work... or is the rest of the machinery clever enough that this won't be problem?
  
There is some logic to handle compiling projects sequentially (because our BSP implementation required it, you can check the `compile` implementation of `BloopBspServices` if you're curious). The addition of this logic caused us to also tweak the implementation of `CompilationTask.compile` to "aggregate" compilation and not try projects that had failed before in the sequential compilation. This approach was only meant to be temporary and is wrong. On the one hand, it compiles the projects sequentially even if they have no dependency between them. On the other hand, the internals are messy and too complex.
  
The right way to handle different projects in `compile` and `test` is to use the notion of `Aggregate` I introduced in this comment. `CompilationTask.compile` now takes a `Dag` of a project, so all you need to do is to change the call-site of `Tasks.test` and `CompilationTask.compile` to aggregate the DAG of the projects in one via `Aggregate` and then pass this aggregate node to the mentioned implementations. `CompilationTask.compile` should immediately work, whereas `Tasks.test` may need some changes to support parallelism.
  
I would start supporting only compilation, and then you can move to supporting test from there.
  
I hope I have provided enough background to tackle this issue. Let me know if you need help.

**Comment by BardurArantsson** [comment]
Thank you very much for the extra info. I'll definitely cherry-pick that and build off Dag!

**Comment by BardurArantsson** [comment]
So, I've been trying to have a little stab at this... I think I can manage most of the issue, but I have a around the code here: https://github.com/scalacenter/bloop/pull/667/files#diff-76ca9fb9d1dc844f02765b2cf8ff9e42R161

I'm wondering about how to handle the State... it it supposed to be threaded around like I'm doing in the WIP code? (It seems a little weird to thread it around explicitly since we're already in a monadic context, but I suppose there's nowhere to stash it in a Task...)

I was actually going to ask a second question, around how to handle watch(), but I see that the Project is only used for a message, so that should actually be easy enough.

**Comment by jvican** [comment]
Let's continue the discussion in the PR :+1:

**Comment by jvican** [comment]
Fixed by https://github.com/scalacenter/bloop/pull/772
