### ISSUE TITLE
Don't ignore changes to unmanaged resource files

### ISSUE THREAD

**Issue by dzamlo** [scalacenter/bloop#586]
Currently, resources files are copied when you run `sbt bloopInstall`. If you change one of the resources files afterwards the changes are ignored.
By ignored I means two things:
1) `bloop run`/ `bloop test` will use the resources as when you ran `sbt bloopInstall`
2) when using `bloop run -w ...` /`bloop test -w ...`, the changes to the resources files do no trigger a new run

This means that every time you modify one of the resources files, you need to run `sbt bloopInstall` again.

For 1), adding the resources folder(s) to the classpath solves the issue in the simple case, but I don't know if there is some situation where this doesn't work.

For me, 2) is less of an issue. Adding the resource folder to `sources` is not enough, the changes are detected but do not trigger a rerun. You could add a new config key for folders that are watched for changes and rerun the  application/tests when anything change in it.

**Comment by jvican** [comment]
Thanks for opening this ticket Loïc. It is true that a change in a resource file (like an xml file in a resources directory) requires the execution of `sbt bloopInstall` so that bloop can pick the change up (this happens because sbt, and our integration, copy the resources file to the classes directory before running compile, test or run).
  
As you poing out, a way to solve this issue is if we add the resource files found to the classpath. I think this would cover most of the cases. However, this is not the default in other build tools and, in some cases, the compiler may disable optimizations (like caching the classpath) if files that are not zip and JARs are found in the classpath. The long-term solution would be to add the resources files to the classpath and fix the compiler to avoid disabling these optimizations (possibly under a flag).
  
> For me, 2) is less of an issue. Adding the resource folder to sources is not enough, the changes are detected but do not trigger a rerun. You could add a new config key for folders that are watched for changes and rerun the application/tests when anything change in it.
  
We can do two things:
  
1. Add the resources folder to the sources configuration key, add the resources to the classpath and then have Bloop force the `run` or `test` if the classpath has been changed from the previous run; or,
2. Add a `resources` key in the configuration file (only for unmanaged resources, that is, those that are not generated by the build like a log configuration file or a properties file), and then have Bloop trigger `run` or `test` if something in that folder changes.
  
I lean towards the second one as we don't need to fiddle with the classpath and conceptually speaking it makes sense to add a `resources` field to the configuration file (this is something that had already crossed my mind before).
