### ISSUE TITLE
Source-based project references are failing in sbt

### ISSUE THREAD

**Issue by vimalaguti** [scalacenter/bloop#675]
Hi, I'm using the stable version of bloop 1.0 with sbt 1.2.4

In my build.sbt there are 2 subprojects and one of them depends on a projectRef like this:

ProjectRef(uri("git://github.com/a8m/pb-scala#master"), "pb-scala")

As stated in the wiki installation page, I also added the line
bloopAggregateSourceDependencies in Global := true

But still, every time I run a command, it tells me : 
[E] Key not found: pb-scala

If I look in the .bloop folder, there is no pb-scala.json so I generated the json bloop directly from this subproject and copied them in the main folder along with the others.
This way it starts compiling, but of course compilation breaks with a class not found.

**Comment by jvican** [comment]
Hello @vimalaguti, this issue is caused by sbt's limitations around source dependencies. When you add a plugin in your build and you're using source dependencies, the plugin is not added to the build of the source dependencies (e.g. the build containing `pb-scala`) and therefore the configuration file for that project is never generated.
  
This is missing from our docs, but if you want source dependencies to work with bloop you need to add the bloop plugin globally (check the sbt docs in order to know how to do that). The solution for this problem really needs to come from sbt. I would also encourage against the use of source dependencies in sbt, they are broken in surreptitious ways.
