### ISSUE TITLE
Propagate main class defined from the sbt build

### ISSUE THREAD

**Issue by tindzk** [scalacenter/bloop#718]
As per #716, the detection of main classes is restricted to classes defined within the project. In the case of Play, the sbt project already sets the main class correctly:

```shell
[play-scala-seed] $ show mainClass
[info] Some(play.core.server.ProdServerStart)
```

It would be useful to use this value and set it in the Bloop configuration file such that it does not have to be passed as a command-line parameter.

**Comment by jvican** [comment]
@tindzk Do you feel like taking a stab at this? Should take only a few minutes :smile:

**Comment by tindzk** [comment]
Sure, I will have a look.

**Comment by jvican** [comment]
@tindzk Great! The configuration field for the main class is already there, we just need to propagate it with something like:
  
```scala
        val jvmConfig = Config.JvmConfig(Some(javaHome.toPath), javaOptions.toList)
        val mainClass = Keys.mainClass.in(config).value
        Config.Platform.Jvm(jvmConfig, mainClass)
```
  
where `config == Keys.configuration.value`. We should probably also do the same for Gradle, Maven and mill if we're not doing it there, and add tests for gradle and sbt (in sbt, you can add a check in one of the scripted tests that checks the contents of the JSON configuration files).

**Comment by jvican** [comment]
We cannot depend on `mainClass` directly in sbt because it forces the compilation of projects (internally, `mainClass` depends on `discoveredMainClasses` which triggers compilation during `bloopInstall`, which makes the process slow).
  
As there is no way to avoid that in sbt, I've introduced a `bloopMainClass` setting that can be set just as `mainClass` and that users can use to avoid duplicating the main class every time they want to run an application. There is no better solution than this.
