### ISSUE TITLE
Source dependencies' resources are not available

### ISSUE THREAD

**Issue by tkroman** [scalacenter/bloop#738]
For source dependencies it's normal to have `application.conf` be assembled from (automatically merged) `application.conf`s of all subprojects. Right now this is not the case which results in test failing with 

```
  Cause: com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'foo'
```

if that key is specified in dependency's config.

Note that the right entry is present in classpath in `toplevel-test.json`, it's just that there are no resources copied for subprojects.

**Comment by tkroman** [comment]
I tried installing local build with https://github.com/scalacenter/bloop/pull/730, still doesn't work: project only contains top-level resources. OTOH classpath is aggregated in the sense that it contains paths to subprojects' classes. @jvican do you think it makes sense to do the same for `resources` field?

**Comment by jvican** [comment]
If this has to do with resources, this is fixed in the latest master with https://github.com/scalacenter/bloop/pull/730 could you install 1.0.0+394-4601df7f and confirm it fixed this issue?

**Comment by tkroman** [comment]
Unfortunately it is not. My last message is exactly about that :)

**Comment by tkroman** [comment]
I tried to fix it, but can’t figure out how to make `bloopResourceTask` aware of project’s dependencies+aggregates in a way that would allow to read their `resources` key.

**Comment by jvican** [comment]
Thanks for taking a stab at this!

> Fully sbt-compatible behavior would be for this to also contain all the resource directories of benchmarks etc.
  
In master, resources are included transitively by bloop [here](https://github.com/scalacenter/bloop/blob/master/frontend/src/main/scala/bloop/data/Project.scala#L73-L86). So bloop already tries to imitate the current behavior in sbt and other build tools.
  
The current implementation tries to smartly put resources right in front of the classes directory of the same project (because order matters, and I want to respect the order of the build tool classpath).
  
https://github.com/scalacenter/bloop/pull/742 confirms this description with a test case. I have an intuition that your problem has to do with the order of resources, not the fact that they are not added (as they are).
  
Can you run the application with `--verbose` and check what the classpath passed to the JVM is? Furthermore, can you check that the JSON files of your project have the `resources` populated, too?

**Comment by tkroman** [comment]
Just ran from master's HEAD, works like a charm. Thanks for paying attention to this @jvican!
