### ISSUE TITLE
Gradle project dependency issues

### ISSUE THREAD

**Issue by Arthurm1** [scalacenter/bloop#800]
I don't think the Gradle plugin handles some types of project dependencies. e.g X depends on Y depends on Z.

The Gradle test: `ConfigGenerationSuite.worksWithSeveralScalaProjects` has Project B which depends on Project A and C.
If I add a Project D which depends on Project B then Project A's _jar_ rather than its _classes_ directory is included in Bloop's classpath and Project C is not on the classpath at all.

I think the first issue (Project A included as a jar rather than included as another classes dir) means that project dependencies on other projects have to be recursively queried to find their classes dir.

I think the second issue (Project C not being on the classpath at all) is down to Gradle having a separate compile classpath and runtime classpath and Bloop not.  For now I'd suggest adding Gradle's runtime & compile classpath to Bloop's classpath.

**Comment by jvican** [comment]
@Arthurm1 Thanks for the ticket. Let me think about what the best way to proceed here is and will get back to you when I've made my mind :smile:.

**Comment by Arthurm1** [comment]
I'm wondering whether it's better for Bloop to handle transitive dependencies rather than the integration plugins.

Currently (AFAIK) if project B depends on Project A then the files would be something like...

**A.json:**
```json
"classpath", [ "/cache/coursier.jar" ]
"classesDir" : "/A/classesDir"
```

**B.json:**
```json
"dependencies" : [ "A" ],
"classpath" : [ "/A/classesDir",
                "/cache/coursier.jar",
                "/cache/logging.jar" ]
```

It would be nice if Bloop automatically resolved project dependencies into the classpath when it loaded the json files.
So A's classesDir and A's classpath would not need to be in B's classpath in B.json.
The benefit of this is that each build integration (gradle, sbt, mill etc.) would no longer need to resolve transitive project dependencies - Bloop would do this in code once.
This would also simplify the json files and mean that I could add a library dependency to A.json without the need to alter B.json.

I'd go further than this and get rid of the separation between dependencies and classpath in the json file and instead have something like...

**A.json:**
```json
"dependencies" : [ { "library" : "/cache/coursier.jar" } ]
"classesDir" : "/A/classesDir"
```

**B.json:**
```json
"dependencies" : [ { "project": "A" },
                   { "library" : "/cache/logging.jar" } ]
```
Then the classpath ordering is maintained and the dependencies can be extended which brings me to runtime and compile time classpaths.

If I write a project that uses JDBC and I have a MySQL database then I have to include the MySQL driver in the project but I don't want to be able to access its classes directly from my code and I don't want the LSP prompting me on class completion with classes from the MySQL jar - I want to use pure JDBC.  So I'd like to be able to declare that dependency as a runtime dependency....

**jdbcProject.json**
```json
"dependencies" : [ { "library" : "/cache/MySQL.jar",
                     "pathType" : "runtime"  } ]
```
I should be able to declare project dependencies as runtime as well.

My last suggestion would be to allow dependencies to be exported to other projects....
If I included the Coursier library in my project it will bring in Cats.  Now I confess that I don't know if the Coursier public API exposes Cats classes but if it doesn't then I don't want to be able to access Cats classes in my project and be prompted in the LSP with them on class completion.  But if it does then I do.
So ideally Coursier could spec its json files in the following ways...
**CoursierExposingCats.json**
```json
"dependencies" : [ { "library" : "/cache/cats.jar",
                     "pathType" : "compiletime",
                     "exported" : "true"  } ]
```
**CoursierNOTExposingCats.json**
```json
"dependencies" : [ { "library" : "/cache/cats.jar",
                     "pathType" : "compiletime",
                     "exported" : "false"  } ]
```
**MyProject.json**
```json
"dependencies" : [ { "library" : "/cache/coursier.jar",
                     "pathType" : "compiletime"  } ]
```

Sorry for the stream of consciousness, and for the bad JSON.
Hopefully these 4 points make sense.  They're feedback from using large Gradle projects with many interdependencies and from playing around with your Gradle integration to get transitive dependencies to work.

**Comment by jvican** [comment]
Obtaining the classpath directly from the build tool was something done on purpose because bloop's output has to be as compatible as that of the build tools. Resolving the project dependencies and adding them in the classpath is problematic because the order of the entries in the classpath can not match the order of the entries in the build tool's classpath, and that would result in potentially inconsistent compilation results.
  
Another benefit of having an explicit classpath in the configuration files is that users can inspect them to obtain a valid classpath. This is important for clients wanting to run an application on their own, for example.
  
However, there's some middle ground for a hybrid solution: if build tools do not export a full compile-time classpath, we could complete the classpath ourselves. That is something that I can get behind now because it requires no changes to the configuration files.
  
In other news, handling runtime dependencies is something that should be dealt with in the future. I agree we need to find a solution for that. However, I will not have a look at them any time soon since they are not popular and there are more important aspects to iron out.
  
@Arthurm1 As a starting point, could you look into handling transitive dependencies in the gradle plugin and adding them to the classpath, as we currently do for the rest of the build tools?
