### ISSUE TITLE
Race-condition with `classes.bak` directories

### ISSUE THREAD

**Issue by propensive** [scalacenter/bloop#812]
Bloop appears to create temporary snapshot directories called `classes.bak` during compilation. It appears that concurrent access to these directories is the cause of occasional race conditions (also seen by @jastice), I suspect, because the directory is created by two different threads concurrently, then deleted by one thread before the other thread has finished reading it.

**Comment by jvican** [comment]
If you're compiling the same module concurrently, then it's normal this is happening. Why do you need to compile them concurrently?
  
This is not a bug, it's an expected behavior given that we don't yet support concurrent compilation in different clients. This is currently what I'm working on and will be ready soon.

**Comment by jvican** [comment]
Ah, I think I understand what's going on here. You have all classes directories inside a folder `target` and what happens is that the compilation of two projects that are independent would hit the `classes.bak` because we use the same classes directory always...

Right. This is indeed a bug. We can merge the solution in your PR so that you have an on-merge release you can use for now. However, this bit will probably change in the next major release as I'm reworking the logic handling the class file manager.
