### ISSUE TITLE
Compilation of scalameta paradise macros doesn't finish

### ISSUE THREAD

**Issue by jastice** [scalacenter/bloop#817]
1. Clone https://github.com/JetBrains/intellij-scala
2. `sbt bloopInstall` (sbt-bloop 1.2.5)
3. `bloop compile macros --verbose`
4. The compile never completes.

The last output shown is 
```
[D] [zinc] The Scala compiler is invoked with:
	-target:jvm-1.8
	-deprecation
	-Xplugin:/Users/jast/.ivy2/cache/org.scalameta/paradise_2.12.7/jars/paradise_2.12.7-3.0.0-M11.jar
	-Ycache-plugin-class-loader:none
	-bootclasspath
	/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/sunrsasign.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/classes:/Users/jast/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.12.7.jar
	-classpath [...]
```

**Comment by jvican** [comment]
So it looks like some changes I did in zinc broke scalameta paradise because it is a plugin that is hijacking both the parser and the analyzer via runtime reflection. Any of those injections could be the culprit (my bet would be on the unit parser).
  
I'll look at how I can fix this so that I can let the intellij-scala and cats team to use bloop, but keep in mind that Scalameta Paradise is a plugin that has been publicly archived and is no longer maintained. I recommend people stop using it, otherwise we need to deal with the price of maintaining all of these archaic setups and our resources are limited /cc @ytaras @jastice @kailuowang @mutcianm

**Comment by ytaras** [comment]
Here's a scenario where compilation doesn't hang, but macro expansion is not performed:
https://github.com/ytaras/tagless_failure_showcase

**Comment by mutcianm** [comment]
AFAIK, we only use scalameta/paradise in tests, not sure how this affects ordinary project compilation

**Comment by jvican** [comment]
> AFAIK, we only use scalameta/paradise in tests, not sure how this affects ordinary project compilation

Bloop needs to compile the tests too, so if the tests depend on scalameta/paradise they fail. Looks like it would simplify your setup if you were to finally remove support for the abandoned Scalameta macros.

**Comment by kailuowang** [comment]
@jvican thanks for pinging me. The good news is that cats-tagless is migrating away from scalameta macro. 
https://github.com/typelevel/cats-tagless/pull/22

**Comment by jvican** [comment]
Happy to hear that @kailuowang Let me know if there any more blockers to using bloop
