### ISSUE TITLE
Lightweight way to update dependencies

### ISSUE THREAD

**Issue by tkroman** [scalacenter/bloop#842]
This is more on the side of questions/ideas than a new feature request: would it be possible/sensible/"worthy" to provide a way to update bloop's project definitions by some command like `bloop update-dependencies --add org::proj:ver foo` so that managing dependencies didn't incur eg `sbt bloopInstall` overhead?

**Comment by jvican** [comment]
@tkroman Thanks for the proposal!
  
Unfortunately, I don't think it's in the scope of bloop to carry out these tasks. The design of the build server avoids intentionally handling dependencies, that's a task of the build tool generating bloop configuration files.
  
In the future, I have some ideas to make the `bloopInstall` process faster. In general, `bloopInstall` is already quite fast when you have an open sbt session, it usually takes between 6s and 10s to regenerate configuration files (triggering resource generators, dependency updates, etc) for a medium-sized project. We pay a bigger cost when an sbt session is not open (sbt needs to warm up, populate caches, etc) and even a bigger one when using Metals because "Import Build" injects global settings that disable all the caches and slow sbt down by a big margin. There are some ideas to speed this up by adding these settings to a gitignore local .sbt file instead so that caches are preserved across sbt instances.
  
In the case of the CI, which I suspect it's your case, we cannot do much to speed up `bloopInstall`; usually sbt is slow when starting up in an environment like Docker.
  
What I suspect might be beneficial is to cache configuration files under `.bloop` if the build has not changed (which should avoid the `bloopInstall` step in a significant number of your CI runs).
  
To do that, you'd need to hash the build sbt files and Scala files under `.project` and use that as the cache key. Whenever the hash changes, you retrigger `bloopInstall`.
  
We don't have this code in Bloop but I would welcome a contribution adding this mechanism to our sbt build plugin. If you're interested we can work out the details of how `bloopInstall` could be a no-op if the hash is the same.

**Comment by ivanopagano** [comment]
I would say that it might become limiting in general for bloop to only work through sbt, to manage dependencies.

I didn't check out the latest docs, but thinking about being independently able to define project dependencies could be a reasonable goal.

Sorry if I'm missing critical aspects

**Comment by jvican** [comment]
> I would say that it might become limiting in general for bloop to only work through sbt, to manage dependencies.
  
It is limiting for sure, but I embrace this limitation. I don't intend to solve the problem of sbt being slow, I intend to solve the problem of compiling as fast as possible. Personally I think of this limitation as a feature.

**Comment by ivanopagano** [comment]
Ok, I might've misunderstood. Looking at the github page, I get that bloop works with alternative build tools too (maven, gradle, mill), right?

If so, then my worries are much more put at ease.

**Comment by jvican** [comment]
Yes, I think the official website (https://scalacenter.github.io/bloop/docs/what-is-bloop) summarizes the goals accurately:
  

>Bloop is a Scala build server developed by the Scala Center. It has three main goals:
>
>   * Compiles, tests and runs Scala code as fast as possible
>   * Is an independent and long-lived process reusable by multiple clients
>   * Integrates easily with build tools, command-line applications, editors and custom tooling

**Comment by ivanopagano** [comment]
Sorry, my bad

**Comment by tkroman** [comment]
For me biggest issue wrt sbt<->bloop is not `bloopInstall` which is obviously fast enough, but the time of sbt startup, which can get uncomfortable. Maybe instead of putting this into sbt plugin we could have a "semi-external" hasher that would be flexible enough to merit either its own subproject or even inclusion in bloop core? i.e. if it would be made possible to track changes to hashes of not only build.sbt, but also mill's configs etc, do you see this as a possible outcome?

**Comment by jvican** [comment]
>  Maybe instead of putting this into sbt plugin we could have a "semi-external" hasher that would be flexible enough to merit either its own subproject or even inclusion in bloop core? i.e. if it would be made possible to track changes to hashes of not only build.sbt, but also mill's configs etc, do you see this as a possible outcome?
  
Yes, if someone wants to work on this I'd merge it in the repository :+1:. It'd be a simple application that CIs could invoke to sidestep `sbt bloopInstall` altogether if build inputs haven't changed. As you mention, it could be generalized to other build tools.
  
It's a pity sbt is so slow down to start up. It's a big issue especially in CIs.

**Comment by jvican** [comment]
I'm closing this ticket, @tkroman feel free to submit a PR implementing the build hasher 😈  and ping me privately via Gitter if you need any assistance
