### ISSUE TITLE
Bloop fails to compile with "io.tryp" % "splain" compiler plugin enabled.

### ISSUE THREAD

**Issue by kamilkloch** [scalacenter/bloop#844]
With compiler plugin enabled
```scala
addCompilerPlugin("io.tryp" % "splain" % "0.4.0" cross CrossVersion.patch)
```
bloop 1.2.5 fails to compile, sbt succeeds (see attached screenshots).
![Screenshot from 2019-04-11 15-55-50](https://user-images.githubusercontent.com/807154/55963046-598dc080-5c72-11e9-842e-3427bc160a27.png)

![Screenshot from 2019-04-11 15-56-55](https://user-images.githubusercontent.com/807154/55963136-85a94180-5c72-11e9-800e-26e53f7a7c1b.png)

**Comment by jvican** [comment]
Yes, this is a well-known problem. It turns out `splain` is doing reflection-based stuff on the compiler internals assuming they don't change. What spain is doing is "illegal" or "discouraged" and therefore there's nothing we can do in our side to fix this. All I can recommend you is to not use splain.

**Comment by kamilkloch** [comment]
Thanks for a quick clarification.
