### ISSUE TITLE
Run specific main class using BSP

### ISSUE THREAD

**Issue by marek1840** [scalacenter/bloop#859]
It seems a specific main class cannot be runusing `BSP` - which is a problem when there is more than one of them in a project (when there is only one - it will be picked up automatically).

I tried running it with URI for the specific file, but it was failing nonetheless:
```
ERROR URI 'file:///project_root/src/main/scala/a/Main.scala' has invalid format. Example: file:///path/to/base/directory?id=projectName
```

When specifying the main class as an argument for the `RunParams` I got:
```
ERROR Multiple main classes found. Expected a default main class via command-line or in the configuration of project 'a'
Use the following main classes:
 * Main
 * OtherMain
[E] Unhandled error handling request Request(buildTarget/run,Some({
[E]   "target" : {
[E]     "uri" : "file:/home/marek/workspace/oss/metals/tests/slow/target/e2e/codeLens/run/run-code/a/?id=a"
[E]   },
[E]   "arguments" : [
[E]     "Main"
[E]   ]
[E] }),String("7"))
```

It seems that the `BuildTargetIdentifier` is not being used during the main method resoltuion:
https://github.com/scalacenter/bloop/blob/0aec00b8254a660d366c974749a4a1834ce7cdbe/frontend/src/main/scala/bloop/bsp/BloopBspServices.scala#L393-L401

Maybe it can be used like: if the URI resolves to a scala file then it is a main class. Otherwise let's use the current approach

**Comment by jvican** [comment]
The reason why this is not supported in bloop right now is because it's blocked on adding an option to the BSP protocol to pass the main class discovered by "Scala Main Classes request" https://github.com/scalacenter/bsp/blob/master/docs/bsp.md#scala-main-classes-request
  
To support the ability for the client to pass a concrete main class, we should change `buildTarget/run` to have two more fields: 
  
1. `dataKind: String`
2. `data: Option[Json]`
  
like `buildTarget/compile` and `buildTarget/test` have.
  
Like in `buildTarget/test`, we can define a Scala Main Classes request that is equivalen to the Scala Test classes request and pass that to the `data` field of the run request.

**Comment by jvican** [comment]
Fixed by https://github.com/scalacenter/bloop/pull/1025
