### ISSUE TITLE
Bloop sometimes doesn't recompile dependent projects after changes

### ISSUE THREAD

**Issue by torkelrogstad** [scalacenter/bloop#892]
This is a bug I've noticed every now and then while using Bloop and Metals. After changing git branches, dependencies of a project needs recompiling, but Bloop doesn't pick up this. I haven't been able to make a small reproduction, but today it happened to me after first working on https://github.com/bitcoin-s/bitcoin-s-core/pull/465 and then switching to https://github.com/bitcoin-s/bitcoin-s-core/pull/462. Perhaps you'll be able to reproduce by checking out those two PRs. 

The error messages look like this: 

```
compiling core (21 scala sources)
Error while emitting MnemonicCode.scala
assertion failed: Invalid superClass in Lorg/bitcoins/core/util/CryptoUtil$;: Some(Lorg/bitcoins/core/util/BitcoinSLogger;)
Error while emitting Address.scala
assertion failed: Invalid superClass in Lorg/bitcoins/core/util/BitcoinScriptUtil$;: Some(Lorg/bitcoins/core/util/BitcoinSLogger;)
Error while emitting ChainParams.scala
assertion failed: Invalid superClass in Lorg/bitcoins/core/script/constant/BytesToPushOntoStack$;: Some(Lorg/bitcoins/core/util/BitcoinSLogger;
```

**Comment by jvican** [comment]
Thanks for the ticket :+1: I've seen this kind of errors before in https://github.com/sbt/zinc/issues/598 (Zinc is Scala's incremental compiler, which bloop depends on). I might be able to have a look at this error after the 1.3.0 release and submit a fix. I'm closing since there's nothing we can do in bloop to fix it.
