### ISSUE TITLE
Unexpected SocketException with certain Scalatest arguments

### ISSUE THREAD

**Issue by max-leuthaeuser** [scalacenter/bloop#906]
Very similar to #658, running `bloop test foo` fails with:
```
[E] Unexpected error during remote test execution: 'Socket closed'.
[E] Internal error when running tests: sbt.ForkMain$Run$RunAborted: java.net.SocketException: Broken pipe (Write failed)
```
when specifying certain Scalatest arguments with `sbt`. E.g.:
```scala
testOptions in Test := Seq(
  Tests.Argument(TestFrameworks.ScalaTest
     "-oDI", "-W", "30", "30"
   )
)
```

Once these `testOptions` are removed, `bloop test foo` works without any problems.

Setup:
 - `scalacenter/bloop/bloop: stable 1.2.5` via Homebrew
 - `sbt.version=1.2.8`
 - Scala compiler version 2.12.8
 - JDK 1.8

**Comment by tkroman** [comment]
@max-leuthaeuser this is fixed in master, you can clone the repo and install bloop locally by doing 
`sbt install`
and then 

`bin/install.py -n $(git -C nailgun rev-parse HEAD) -c 1.1.0-M14-4 --bloop-home /path/to/home/.bloop -v 1.2.5+430-de714404`

where `v` will be the version generated by `sbt install` (will be visible in logs).

**Comment by jvican** [comment]
Indeed, this is fixed in master, thanks @tkroman for the quick answer :smile:

**Comment by max-leuthaeuser** [comment]
Thanks for the quick answer and solution!
