### ISSUE TITLE
Missing scala in config causes error in 1.3.0-RC1

### ISSUE THREAD

**Issue by Arthurm1** [scalacenter/bloop#921]
If you have a Java-only project without a `scala` section in the Bloop JSON file then the message _failed to compile_ appears with no reason why it failed even with verbose.

This worked in the previous version.

Adding a `scala` section into the JSON file fixes the issue.

FYI: `gradle bloopInstall` doesn't put a Scala section into Java-only projects which I think is correct as where would it get the library version info from.

**Comment by jvican** [comment]
Hey @Arthurm1, thanks for reporting!
  
I tried to reproduce this issue in my macOS box but didn't succeed. I tried compiling only a Java target, with no `scala` section in the JSON file, and the compilation succeeded. However I did reproduce in Windows!
  
It looks like this was caused by our coursier upgrade.

**Comment by Arthurm1** [comment]
Ah - yes I should have said - it's on Windows

**Comment by jvican** [comment]
Alrighty, confirmed the coursier upgrade broke this in Windows and Linux, macOS is not affected because it doesn't use coursier bootstrap. I've just fixed this so I'm adding it into the final 1.3.0 :tada:
