### ISSUE TITLE
Fix unhelpful warning "Ignored CLI test options"

### ISSUE THREAD

**Issue by jrudolph** [scalacenter/bloop#924]
That happens if you add test CLI options to `bloop test --only <some scalatest spec> -- <extra options here>` but it's unclear how test frameworks were detected and how to solve it. Especially, since only a single ScalaTest spec was selected with `--only` in the first place.

There seems to be https://github.com/scalacenter/bloop/issues/662 but is that a general solution?

**Comment by jrudolph** [comment]
Also found

> You have a project with tests of different test frameworks (e.g. Scalacheck and Scalatest) but you're filtering out tests that are part of only one framework (for example, via --only)

on https://scalacenter.github.io/bloop/docs/usage#pass-arguments-to-test but that doesn't seem to work.

**Comment by jrudolph** [comment]
As a reproducer you can try `bloop test akka-http2-support-test --watch --pipeline --only akka.http.impl.engine.http2.Http2ServerSpec  -- -z "GET request in one HEADERS frame"` after checking out and initializing bloop on https://github.com/akka/akka-http.

**Comment by jvican** [comment]
@jrudolph This is fixed in v1.3.0-RC1, I've been using this for a while :smile: Please let me know if that's not the case!
  
The solution to remove this warning is always to pass test framework options to a concrete framework in case there are more than one, that's the solution you mention with `-o`. I think sbt does not have this limitation because it passes arguments to all the test frameworks and waits for them to either succeed or fail (and then log it to the user). I took this approach to avoid confusing logs saying that initializing the test framework is failing.
  
Do you have a better suggestion to handle that scenario?

**Comment by jvican** [comment]
(I'm keeping this open in the spirit of finding a better default for this case, if you don't have any ideas let me know and I'll close the ticket, as the bug is already fixed)
