### ISSUE TITLE
Add option to pipe errors to a file when on file-watch mode

### ISSUE THREAD

**Issue by pjrt** [scalacenter/bloop#937]
`bloop -w` reminds me of `ghcid` (https://github.com/ndmitchell/ghcid) in the way it works. 

One feature `ghcid` has which is quite useful is the ability to pass a file name via a flag `-o` . This will start ghcid as it normally does BUT also pipe the result to a file. The file will also be clears and repopulated whenever ghcid resets (due to a file being changed). 

Such a feature is incredibly useful for editors like vim since they allow you to simple read the file and populate the quickfix list. 

It would be great if `bloop -w` had the same feature.

**Comment by pjrt** [comment]
In case anyone else wants a workaround for now:

```bash
#!/usr/bin/env bash

gitroot=$(git rev-parse --show-toplevel)

function runWhile() {
  while read line; do 
    noColor=$(echo $line | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g")
    case $noColor in
      Watching*)
        cat $raw > $quickfix 2> /dev/null && rm -f $raw
        ;;
      \[E*)
        echo "$noColor" >> $raw
        ;;
      *)
        ;;
    esac
  done > /dev/null
}

if [ $? -eq 0 ]; then
  quickfix=${gitroot}/.git/sbt.quickfix
  raw=${quickfix}.raw
  bloop $@ -w 2>&1 | tee >(runWhile)
else
  echo "Not in a git repo. Running plain Bloop..."
  bloop $@ -w 2>&1
fi
```

**Comment by jvican** [comment]
Thanks for the feature request and explanation!

> Such a feature is incredibly useful for editors like vim since they allow you to simple read the file and populate the quickfix list.

You can use vim with Metals to have access to all of the compiler errors from the editor itself or if that's not enough for your use case you can write your own build client via BSP (maybe based on our bloop CLI) that then populates the server's output to the file.
  
I'm happy to see your workaround though. I'm closing because I prefer not to add support for this in bloop itself.

**Comment by Jacoby6000** [comment]
the problem with metals is that it's a much heavier solution than something that just shows errors.

Many (I might even say most) vim users run with just ctags (or @pjrt's [sctags](https://github.com/pjrt/stags) for scala specifically) and other tooling which is much lighter weight than something like metals.

Adding this feature would allow us to benefit from the speed of bloop's compile times and be able to react to error messages without having to run a large background service which is much more resource intensive.

**Comment by jvican** [comment]
I think that at the moment you want something more lightweight than Metals you’re in the space of implementing your own build client via BSP and that’s what I’d recommend instead.

Bloop has a flexible architecture based on BSP because we want clients to implement their own tools with their own constraints. This is the perfect use case to put that in practice.

**Comment by Jacoby6000** [comment]
Implementing a BSP client is significantly more heavy weight than just
having a build tool write to a file as well as STD out. It seems a bit
overkill to set up an entire build client with Json parsing/serialization
when all that's really necessary is a way to forward build output to a file
at the same time as std out.

**Comment by jvican** [comment]
Yup, might be overkill but I’m not changing my opinion here. Constraining supported features means we can continue to move fast without maintaining all of our users' use cases and dragging future development.

**Comment by pjrt** [comment]
I find the idea of "print to stdout + file" to be "constraining" pretty odd.

But I have no plans on making a PR for that so there's no point in arguing.
