### ISSUE TITLE
Add packaging capabilities to the project

### ISSUE THREAD

**Issue by adamnfish** [scalacenter/bloop#953]
Bloop is optimised for compiling, testing and running projects. This is a great fit for a developer's machine, but in my experience the sbt start time isn't a huge problem on developer machines. They fire up sbt at the start of the working day and hack away thereafter on a nice warm JVM.

In my mind the biggest win would be on our build servers. [Here](https://github.com/guardian/) we have hundreds of builds going through each of our TeamCity build agents every day. Because each one is an isolated build we pay the sbt startup cost and then suffer a slow VM while it runs the tests. For many of our simple applications the sbt start time is the bulk of the build time, and for some of our very large projects we have to optimise the build steps around sbt being slow to parse project definitions. If the build-servers were all running a Bloop server then each project could run every build in isolation on a pre-started and warmed VM.

However, a fundamental part of the CI build process is the ability to package up a production app, with its dependencies (using native packager or some such). AFAICT, Bloop does not yet address this use-case.

Is this on purpose? Is the goal of the tool limited to developer machines? Perhaps Bloop already works here and I've missed something! Is this a known feature that's on the roadmap? Or is this a new idea that needs prioritising?

Perhaps if others have come to the same conclusion they could share their experiences so we can get a clear idea of what challenges this would need to address?

Thanks very much!

**Comment by jvican** [comment]
@adamnfish Thank you for your feedback!

> Is this on purpose?
  
Yes, because:
  
> Bloop is optimised for compiling, testing and running projects.
  
Our focus is only on providing the fastest compile/test/run workflow to developer and to any build client that they use. Anything that is not related to compiling, testing or running needs to be implemented outside of bloop.
  
Bloop is moving towards being the centralized compile server that lots of tools use under the hood. Yes, we have a CLI and you could use it in your CI if you wanted to (it's faster and easier to use than many build tools), but the goal of bloop is not to replace other build tools but to integrate with them and help build tools innovate more but not reinventing the wheel.
  
I know @alexarchambault has been looking into providing packaging/publishing capabilities in coursier, maybe you can open a ticket in the coursier repository to get more info or drop by their gitter channel?

**Comment by adamnfish** [comment]
That makes sense, thanks heaps for the detailed reply. Great to see that the project has such a tight focus :-)
