### ISSUE TITLE
`--help` doesn't mention the `--` pass-through

### ISSUE THREAD

**Issue by ArturGajowy** [scalacenter/bloop#970]
I've noticed that there's no notion of `--` when in `--help` text.
Having it would be helpful.

**Comment by jvican** [comment]
The passthrough is mostly command dependent and it's explained in the quickstart. @ArturGajowy There isn't much we can do here because docs for every command are autogenerated, a more appropiate place to file this feature request would be in case-app, which is what we use to generate CLI arguments. https://github.com/alexarchambault/case-app

**Comment by ArturGajowy** [comment]
Isn't there an option of adding custom doc text for a command?
