### ISSUE TITLE
Watch changes while compilation is happening

### ISSUE THREAD

**Issue by pkolaczk** [scalacenter/bloop#980]
1. Run
 
```
bloop compile `bloop projects` --watch
```

2. Open a multi-module bloop-enabled project in an IDE.
3. Go to Refactoring and Rename a class that's used in multiple modules.
4. See plenty compilation failures (missing class: (new name))
5. Bloop does *not* retry the failed compilation after the renaming is finished.
6. Rerun compilation manually - compiles fine.

Proposed solutions:
A. Watch for changes happening *during* compilation (or any watched action). Detect and record any change since the time the compilation *started*. If such change happens, force another round, because the current compilation session might have missed it. You can be even quite smart with that - e.g. don't restart the whole process, but just add changed source files and source files that failed to compile in the current stage to the invalidated set and start from there.

B. Wait a 0.1 second after detecting a file change before launching compilation. If another change is detected during that time, wait another 0.1s, etc. This is simple and I guess it would work in most cases, avoiding needless recompilation.

**Comment by jvican** [comment]
> Watch for changes happening during compilation (or any watched action)
  
I've tried it but it's quite difficult to get it working reliably. The file watching logic is far from trivial and all changes there heavily affect the cancellation of the processes in negative ways, so this is not a trivial change.
  
> . You can be even quite smart with that - e.g. don't restart the whole process, but just add changed source files and source files that failed to compile in the current stage to the invalidated set and start from there.
  
Thought about it, we have the infrastructure about it but don't want to implement it because it's too complex for little gain.
  
> Wait a 0.1 second after detecting a file change before launching compilation.
  
We're already doing this, too, but not for such a long time. I want file watching to be as snappy as possible so increasing timeout is not an option, assuming the timeout is an issue.
  
It'd be helpful if we had a tiny reproduction or even a test case in `FileWatchingSpec`.

**Comment by pkolaczk** [comment]
> I've tried it but it's quite difficult to get it working reliably. 

I don't understand what's the difficulty here. Can you elaborate a bit more?

There is a file-change detection logic already implemented. The project recompiles fine if I trigger compilation manually after refactoring, even though background compilation failed.

If a change happens *during* compilation, just store the change event into a queue instead of ignoring. When the compilation finishes, check the pending file changes queue. If not empty, force recompile.

> I want file watching to be as snappy as possible so increasing timeout is not an option.
Fair enough.

**Comment by pkolaczk** [comment]
Possibly related: 
https://github.com/sbt/zinc/issues/683
